require("utils")
require("general")
-- require("plugins.packer")
require("plugins.pckr")
require("plugins.dracula")
require("plugins.nvim-dap")
require("plugins.nvim-treesitter")
require("keybindings")
require("lsp.rust-lsp")
require("lsp.python-lsp")
require("plugins.lualine")

