require("utils")
require("general")
require("keybindings")
require("plugins.packer")
require("plugins.dracula")
require("plugins.nvim-dap")
require("plugins.toggleterm")
require("plugins.nvim-treesitter")
require("lsp.rust-lsp")
require("lsp.rust-lsp")
require("plugins.lualine")

